package tokenizer;

public enum DFAState {
	INITIAL_STATE,
	IDENTIFIER_STATE,
	DEC_STATE,
	HEX_STATE,
	PLUS_SIGN_STATE,
	MINUS_SIGN_STATE,
	DIV_SIGN_STATE,
	MUL_SIGN_STATE,
	LESS_SIGN_STATE,
	GREATER_SIGN_STATE,
	EQUAL_SIGN_STATE,
	SEMICOLON_STATE,
	LEFT_BRACKET_STATE,
	RIGHT_BRACKET_STATE,
	COMMA_STATE,
	EXCLAMATION_STATE,//¸ÐÌ¾ºÅ
	ZERO_STATE,
	LEFT_BRACE_STATE,//×ó´óÀ¨ºÅ
	RIGHT_BRACE_STATE,//ÓÒ´óÀ¨ºÅ
	SLASH_STATE,//Ð±¸Ü
	ANNOTATION_SLASH_STATE,//Ð±¸ÜÐÍ×¢ÊÍ
	ANNOTATION_STAR1_STATE,//ÐÇÐÇÐÍ×¢ÊÍ1
	ANNOTATION_STAR2_STATE,//ÐÇÐÇÐÍ×¢ÊÍ2
	CHAR_LITER1_STATE,// '
	CHAR_LITER2_STATE,// 'a    '\"   '\xab   
	CHAR_ESCAPE_LITER_STATE,// '\
	CHAR_HEX_LITER1_STATE,// \x
	CHAR_HEX_LITER2_STATE,// \xA \x0
	STRING_LITER_STATE,// 
	STRING_ESCAPE_LITER,
	STRING_HEX_LITER1_STATE,
	STRING_HEX_LITER2_STATE,
}
